In [1]:
import os
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [2]:
os.chdir("..")
print(os.getcwd())

d:\MLOps\End-To-End-MLOps-Projects\Customer-Churn-Prediction-MLOps

In [3]:
print(os.listdir("data/raw"))

['customer_churn.csv']

In [4]:
RAW_DATA_PATH = os.path.join("data", "raw", "customer_churn.csv")
print(RAW_DATA_PATH)

data\raw\customer_churn.csv

In [5]:
df = pd.read_csv(RAW_DATA_PATH)
df.head()

,Names,Age,Total_Purchase,Account_Manager,Years,Num_Sites,Onboard_date,Location,Company,Churn
0,Cameron Williams,42.0,11066.80,0,7.22,8.0,2013-08-30 07:00:40,"10265 Elizabeth Mission Barkerburgh, AK 89518",Harvey LLC,1
1,Kevin Mueller,41.0,11916.22,0,6.50,11.0,2013-08-13 00:38:46,"6157 Frank Gardens Suite 019 Carloshaven, RI 1...",Wilson PLC,1
2,Eric Lozano,38.0,12884.75,0,6.67,12.0,2016-06-29 06:20:07,"1331 Keith Court Alyssahaven, DE 90114","Miller, Johnson and Wallace",1
3,Phillip White,42.0,8010.76,0,6.71,10.0,2014-04-22 12:43:12,"13120 Daniel Mount Angelabury, WY 30645-4695",Smith Inc,1
4,Cynthia Norton,37.0,9191.58,0,5.56,9.0,2016-01-19 15:31:15,"765 Tricia Row Karenshire, MH 71730",Love-Jones,1

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 900 entries, 0 to 899
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Names            900 non-null    object
 1   Age              900 non-null    float64
 2   Total_Purchase   900 non-null    float64
 3   Account_Manager  900 non-null    int64
 4   Years            900 non-null    float64
 5   Num_Sites        900 non-null    float64
 6   Onboard_date     900 non-null    object
 7   Location         900 non-null    object
 8   Company          900 non-null    object
 9   Churn            900 non-null    int64
dtypes: float64(4), int64(2), object(4)
memory usage: 70.4+ KB

In [7]:
df.isnull().sum()

Names              0
Age                0
Total_Purchase     0
Account_Manager    0
Years              0
Num_Sites          0
Onboard_date       0
Location           0
Company            0
Churn              0
dtype: int64

In [8]:
df['Age']=df['Age'].astype('int64')
df['Num_Sites']=df['Num_Sites'].astype('int64')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 900 entries, 0 to 899
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Names            900 non-null    object
 1   Age              900 non-null    int64
 2   Total_Purchase   900 non-null    float64
 3   Account_Manager  900 non-null    int64
 4   Years            900 non-null    float64
 5   Num_Sites        900 non-null    int64
 6   Onboard_date     900 non-null    object
 7   Location         900 non-null    object
 8   Company          900 non-null    object
 9   Churn            900 non-null    int64
dtypes: float64(2), int64(4), object(4)
memory usage: 70.4+ KB

In [10]:
df=df.drop(columns=['Names','Onboard_date','Location','Company'],errors='ignore')

In [11]:
df.head()

   Age  Total_Purchase  Account_Manager  Years  Num_Sites  Churn
0   42        11066.80                0   7.22          8      1
1   41        11916.22                0   6.50         11      1
2   38        12884.75                0   6.67         12      1
3   42         8010.76                0   6.71         10      1
4   37         9191.58                0   5.56          9      1

In [12]:
X=df.drop(columns=['Churn'])
y=df["Churn"]

In [15]:
X.columns

Index(['Age', 'Total_Purchase', 'Account_Manager', 'Years', 'Num_Sites'], dtype='object')

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [16]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.transform(X_test)

In [17]:
processed_df = pd.DataFrame(X_train_scaled, columns=X.columns)
processed_df['Churn'] = y_train.reset_index(drop=True)

In [20]:
processed_df.head()

        Age  Total_Purchase  Account_Manager     Years  Num_Sites  Churn
0 -1.940415        0.609254         1.045478 -0.041546  -0.349420      1
1 -0.267443       -1.355415         1.045478 -0.774203   1.354300      0
2 -0.769335        2.039121        -0.956501  1.289842  -1.485234      0
3  0.234448       -1.709781        -0.956501  0.486282  -0.349420      0
4  0.736340        0.594198         1.045478  2.093401   0.786393      0